apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eceuserapi
  template:
    metadata:
      labels:
        app: eceuserapi
    spec:
      containers:
        - name: app-container
          image: noepham/eceuserapi:latest
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          volumeMounts:
            - mountPath: "/data"
              name: redis-storage
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
