apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pvc
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./redis-data"  # Update with your actual path
