apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: eceuserapi-service
spec:
  selector:
    app: eceuserapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
