version: '3.4'

services:
  eceuserapi:
    image: eceuserapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: ["node", "src/index.js"]
