services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379:6379

  eceuserapi:
    image: eceuserapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REDIS_HOST: redis  # Update this line
    ports:
      - 3000:3000
    volumes:
      - ./src:/src
      - /src/node_modules
    links:
      - redis
