---
- name: Health Check for userapi App and Redis Server
  hosts: redis_server
  become: true
  gather_facts: true
  connection: ssh

  vars:
    userapi_health_check_url: "http://localhost:3000"
    redis_health_check_port: 6379

  tasks:
    - name: Check if Node.js and npm are installed
      become: true
      command: "command -v node"
      register: node_installed
      ignore_errors: true

    - name: Ensure Node.js and npm are installed
      become: true
      block:
        - apt:
            name: nodejs
            state: present
        - apt:
            name: npm
            state: present
      when: node_installed.rc != 0

    - name: Install required Node.js packages
      become: true
      npm:
        name: "{{ item }}"
        global: no
        state: present
      loop:
        - "body-parser"
        - "express"
        - "mixme"
        - "nodemon"
        - "redis"

    - name: Start the userapi app
      become: true
      command: "npm start"
      args:
        chdir: "../../userapi"

    - name: Wait for the app to start
      become: true
      wait_for:
        host: "localhost"
        port: 3000
        timeout: 60

    - name: Perform health check for userapi app
      become: true
      uri:
        url: "{{ userapi_health_check_url }}"
        return_content: yes
      register: userapi_health_check_result

    - name: Display userapi health check result
      become: true
      debug:
        var: userapi_health_check_result.json

    - name: Perform health check for Redis server
      become: true
      wait_for:
        host: "localhost"
        port: "{{ redis_health_check_port }}"
        timeout: 10
      ignore_errors: true
      register: redis_health_check_result

    - name: Display Redis health check result
      become: true
      debug:
        var: redis_health_check_result
  