name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [14.x] # Use a valid Node.js version here

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 # Change to v2 as it was the latest at my last knowledge update
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies and Build
      run: |
        cd labs/lab03
        npm install
        npm run build --if-present
      working-directory: ./labs/lab03

    - name: Run Tests
      run: |
        cd labs/lab03
        npm test
      working-directory: ./labs/lab03
