# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Redis container example
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  runner-job:
    runs-on: ubuntu-latest
  container-job:
    runs-on: ubuntu-latest
    container: node:16-bullseye
    
    services: 
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./labs/lab03
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check out repository code
    - uses: actions/checkout@v4
    - name : Install dependencies
      run: npm ci
      # working-directory: './labs/lab03'
    - name : Connect to Redis 
      run: node client.js
      env:
        REDIS_HOST: redis
        REDIS_PORT: 6379
    - run: npm run build --if-present
    - run: npm test
